### ISSUE TITLE
index error: list index out of range

### ISSUE THREAD

**Issue by naixiangxiaozi** [gencorefacility/reform#1]
To whom it may concern,
The reform is perfect for our analysis! And we are the newer one to use this and don't know how to solve the problem that shows " index error: list index out of range." Could you please help us to solve this problem and here is the screenshot of the error shows
![8711545248167_ pic_hd](https://user-images.githubusercontent.com/42306818/50252358-582b4600-03ac-11e9-815b-302b22334357.jpg)

**Comment by naixiangxiaozi** [comment]
Thank you for your quick response.


The attached files are used for the deletion of a reference sequence and addition of the novel sequence.


Could you please help us to solve the problem.


Thank you!


Best,

Hua

________________________________

**Comment by mohammedkhalfan** [comment]
Hi Hua, please email me the files at mk5636@nyu.edu
