### ISSUE TITLE
New Chromosome

### ISSUE THREAD

**Issue by JBreunig** [gencorefacility/reform#7]
Wonderful work on this!  It worked well for me in terms of inserting into a chromosomal locus.

However, is there a way to insert a "new" chromosome (i.e. just for transgenic elements--EGFP, TdTomator, etc.)?

**Comment by tilofreiwald** [comment]
To have it in a "new" chromosome you could just manually append the GFP component to the genome.fa file as outlined here: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_mr
